### ISSUE TITLE
Binary Build Fails if Project Path Contains Spaces

### ISSUE THREAD

**Issue by JHawkley** [abbr/deasync#118] opened 2019-07-27 00:41 UTC
I've been attempting to install the `deasync` package but been running into problems doing so.

The problem seems to happen when `g++` executes during the build process and tries to load the `node-addon-api` package from the `node_modules` directory.

Given that my project path is:
`/mnt/c/Other Projects/babel-async-traversal`

I get the following error during the installation process:
```
make: Entering directory `/mnt/c/Other Projects/babel-async-traversal/node_modules/deasync/build'
  CXX(target) Release/obj.target/deasync/src/deasync.o
g++: error: Projects/babel-async-traversal/node_modules/node-addon-api: No such file or directory
make: *** [Release/obj.target/deasync/src/deasync.o] Error 1
make: Leaving directory `/mnt/c/Other Projects/babel-async-traversal/node_modules/deasync/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/USER/.nvm/versions/node/v11.13.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
```

Note that `g++` is searching for a directory called `Projects/babel-async-traversal/node_modules/node-addon-api` and finding that it doesn't exist.  It sure doesn't.  It seems that at some point, the path gets split at the space character of the `Other Projects` directory.

Searching for a possible cause, [this issue](https://github.com/formulahendry/vscode-code-runner/issues/248) suggests that the path should be wrapped in double-quotes before passing it to `g++` to ensure that it takes the string as a single path, and not two paths delimited by a space.

A small change in [this file](https://github.com/abbr/deasync/blob/master/binding.gyp), where the location of the `node-addon-api` package is determined by executing Node, is likely all that is needed to resolve this issue.

**Comment by abbr** [comment] 2019-12-26 01:39
Which OS and node version?

**Comment by JHawkley** [comment] 2019-12-26 11:31
It's been a while.  I have updated Node since this time.  I know I was using Windows 10's WSL Legacy kernel (which I am in the process of finally migrating from) and *probably* Node 7.10 or higher (for the `async`/`await` support).

Let me give this another go and let you know if it still fails.

Ah, it installed fine this time.  I since adjusted the project so it didn't need deasync, however, so it's not a problem for me at this point.  Good to know it's working under my current configuration, which is WSL Legacy kernel with Node 11.13.0.

**Comment by abbr** [comment] 2019-12-26 14:21
Thanks for the info. I can reproduce the issue in WSL but not in other envs. The bug seems exists in node-gyp and won't be fixed in foreseeable future according to [issue #65](/nodejs/node-gyp/issues/65). Deasync includes pre-compiled binaries for linux x64 so compilation shouldn't happen in first place. Due to libc runtime version mismatch, the pre-compiled binaries is probably incompatible with your host env, causing the compiling took place. I have fixed libc version mismatch issue since deasync@0.1.19 for node 10+ so it should prevent this issue in the future.

**Closed by abbr** 2019-12-26 14:21 UTC
